// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace Formatters.Data.Beans
{
    public sealed class t_monsterBeanFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Data.Beans.t_monsterBean>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Data.Beans.t_monsterBean value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(14);
            writer.Write(value.t_id);
            writer.Write(value.m_t_name);
            writer.Write(value.t_monster_id);
            writer.Write(value.t_monster_ui);
            writer.Write(value.t_monster_type);
            writer.Write(value.t_star);
            writer.Write(value.t_lv);
            writer.Write(value.t_head);
            writer.Write(value.t_camp);
            writer.Write(value.t_type);
            writer.Write(value.t_battle_prefab);
            writer.Write(value.t_scale);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.t_skill, options);
            writer.Write(value.t_att);
        }

        public global::Data.Beans.t_monsterBean Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Data.Beans.t_monsterBean();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.t_id = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.m_t_name = reader.ReadInt32();
                        break;
                    case 2:
                        ____result.t_monster_id = reader.ReadInt32();
                        break;
                    case 3:
                        ____result.t_monster_ui = reader.ReadInt32();
                        break;
                    case 4:
                        ____result.t_monster_type = reader.ReadInt32();
                        break;
                    case 5:
                        ____result.t_star = reader.ReadInt32();
                        break;
                    case 6:
                        ____result.t_lv = reader.ReadInt32();
                        break;
                    case 7:
                        ____result.t_head = reader.ReadInt32();
                        break;
                    case 8:
                        ____result.t_camp = reader.ReadInt32();
                        break;
                    case 9:
                        ____result.t_type = reader.ReadInt32();
                        break;
                    case 10:
                        ____result.t_battle_prefab = reader.ReadInt32();
                        break;
                    case 11:
                        ____result.t_scale = reader.ReadInt32();
                        break;
                    case 12:
                        ____result.t_skill = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 13:
                        ____result.t_att = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
