// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace Formatters.Data.Beans
{
    public sealed class t_globalBeanFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Data.Beans.t_globalBean>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Data.Beans.t_globalBean value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(7);
            writer.Write(value.t_id);
            writer.Write(value.t_int_param);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.t_string_param, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.List<int>>(formatterResolver).Serialize(ref writer, value.t_array_param, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Data.SelfDefineType.SkillTarget>(formatterResolver).Serialize(ref writer, value.t_enum_Param, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.List<global::Data.SelfDefineType.SkillTarget>>(formatterResolver).Serialize(ref writer, value.t_enumArray_Param, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Data.SelfDefineType.TestClass>(formatterResolver).Serialize(ref writer, value.t_testclass_Param, options);
        }

        public global::Data.Beans.t_globalBean Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Data.Beans.t_globalBean();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.t_id = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.t_int_param = reader.ReadInt32();
                        break;
                    case 2:
                        ____result.t_string_param = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.t_array_param = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.List<int>>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.t_enum_Param = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Data.SelfDefineType.SkillTarget>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.t_enumArray_Param = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.List<global::Data.SelfDefineType.SkillTarget>>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 6:
                        ____result.t_testclass_Param = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Data.SelfDefineType.TestClass>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
