// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace Resolvers
{
    public class ConfigDataResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new ConfigDataResolver();

        private ConfigDataResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = ConfigDataResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class ConfigDataResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static ConfigDataResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(14)
            {
                { typeof(global::System.Collections.Generic.List<global::Data.SelfDefineType.SkillTarget>), 0 },
                { typeof(global::System.Collections.Generic.List<global::Data.SelfDefineType.TestClass>), 1 },
                { typeof(global::System.Collections.Generic.List<global::System.Collections.Generic.List<global::Data.SelfDefineType.SkillTarget>>), 2 },
                { typeof(global::System.Collections.Generic.List<global::System.Collections.Generic.List<int>>), 3 },
                { typeof(global::System.Collections.Generic.List<int>), 4 },
                { typeof(global::System.Collections.Generic.List<string>), 5 },
                { typeof(global::Data.SelfDefineType.SkillTarget), 6 },
                { typeof(global::Data.Containers.t_globalBeanDeserializeProxy), 7 },
                { typeof(global::Data.Containers.t_globalBeanDeserializeProxyData), 8 },
                { typeof(global::Data.Containers.t_languageBeanDeserializeProxy), 9 },
                { typeof(global::Data.Containers.t_languageBeanDeserializeProxyData), 10 },
                { typeof(global::Data.Containers.t_monsterBeanDeserializeProxy), 11 },
                { typeof(global::Data.Containers.t_monsterBeanDeserializeProxyData), 12 },
                { typeof(global::Data.SelfDefineType.TestClass), 13 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ListFormatter<global::Data.SelfDefineType.SkillTarget>();
                case 1: return new global::MessagePack.Formatters.ListFormatter<global::Data.SelfDefineType.TestClass>();
                case 2: return new global::MessagePack.Formatters.ListFormatter<global::System.Collections.Generic.List<global::Data.SelfDefineType.SkillTarget>>();
                case 3: return new global::MessagePack.Formatters.ListFormatter<global::System.Collections.Generic.List<int>>();
                case 4: return new global::MessagePack.Formatters.ListFormatter<int>();
                case 5: return new global::MessagePack.Formatters.ListFormatter<string>();
                case 6: return new Formatters.Data.SelfDefineType.SkillTargetFormatter();
                case 7: return new Formatters.Data.Containers.t_globalBeanDeserializeProxyFormatter();
                case 8: return new Formatters.Data.Containers.t_globalBeanDeserializeProxyDataFormatter();
                case 9: return new Formatters.Data.Containers.t_languageBeanDeserializeProxyFormatter();
                case 10: return new Formatters.Data.Containers.t_languageBeanDeserializeProxyDataFormatter();
                case 11: return new Formatters.Data.Containers.t_monsterBeanDeserializeProxyFormatter();
                case 12: return new Formatters.Data.Containers.t_monsterBeanDeserializeProxyDataFormatter();
                case 13: return new Formatters.Data.SelfDefineType.TestClassFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
